
// Objective-C API for talking to the following Go packages
//
//	github.com/GaoMjun/ladder/bind/ladderclient
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ladderclient_FRAMEWORK_H__
#define __Ladderclient_FRAMEWORK_H__

#include "Ladderclient.objc.h"
#include "universe.objc.h"

#endif
