// Objective-C API for talking to github.com/GaoMjun/ladder/bind/ladderclient Go package.
//   gobind -lang=objc github.com/GaoMjun/ladder/bind/ladderclient
//
// File is generated by gobind. Do not edit.

#ifndef __Ladderclient_H__
#define __Ladderclient_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT void LadderclientRun(NSString* configJsonString);

#endif
